mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/mybatis-config.xml

dbrouter:
  dbCount: 2
  tbCount: 4
  list: db01,db02
  db01:
    url: jdbc:mysql://127.0.0.1:3306/bugstack_01?useUnicode=true
    username: root
    password:
  db02:
    url: jdbc:mysql://127.0.0.1:3306/bugstack_02?useUnicode=true
    username: root
    password:
